### ISSUE TITLE
Profile archiving performance

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-agent#128]
We've already switched to a better gzip implementation in #52 but we still getting report about slow performance especially on Windows. We should investigate how we can make `targz.go` faster and maybe take a look at alternative compression algorithms like `zstd`.

**Comment by edigaryev** [comment]
It seems that this has nothing to do with the compression: providing a raw tar archive and [omitting the `gzip.NewReader()`](https://github.com/cirruslabs/cirrus-ci-agent/blob/b348387cf7486805e1869c2e226acb226d2aba0e/internal/targz/targz.go#L98) step yields negligible difference.

The most slowdown comes from the [io.CopyBuffer()](https://github.com/cirruslabs/cirrus-ci-agent/blob/b348387cf7486805e1869c2e226acb226d2aba0e/internal/targz/targz.go#L155) step: writing to the `io.Discard` instead brings back the performance that is similar of when running on Linux.

Here's rather simplified test case that reproduces the issue:

```go
package main

import (
	"fmt"
	"math/rand"
	"os"
)

const (
	numFilesToCreate = 16_000
	fileSizeBytes = 32_000
)

func main() {
	zeroChunk := make([]byte, fileSizeBytes)

	for i := 0; i < numFilesToCreate; i++ {
		randomFileName := fmt.Sprintf("%d", rand.Uint64())

		out, err := os.Create(randomFileName)
		if err != nil {
			panic(err)
		}

		if _, err := out.Write(zeroChunk); err != nil {
			panic(err)
		}

		if err := out.Close(); err != nil {
			panic(err)
		}
	}
}
```

Results:

![Screenshot 2021-04-16 at 04 33 36](https://user-images.githubusercontent.com/85709/114959057-f3ddfb80-9e6c-11eb-9c09-db4bddfca64c.png)

I've initially thought that this might be caused by the Microsoft Defender's Realtime Protection, similarly to https://github.com/microsoft/Windows-Dev-Performance/issues/27, but running the `Get-MpComputerStatus` and `Set-MpPreference` PowerShell commands results in errors, which likely means [that it's already disabled](https://stackoverflow.com/questions/48960190/powershell-set-mppreference-disablerealtimemonitoring-true-not-working-correct) or the PowerShell [is running in 32-bit mode](https://stackoverflow.com/questions/43881583/add-mppreference-is-not-recognized-as-a-name) 🤔

**Comment by edigaryev** [comment]
Same timings for `docker_builder` with `platform: windows` and `os_version: 2019`:

![Screenshot 2021-04-16 at 04 58 57](https://user-images.githubusercontent.com/85709/114960873-921f9080-9e70-11eb-9d0d-f77a07a62405.png)

**Comment by edigaryev** [comment]
Turns out this was actually Microsoft's Defender. This command:

```
powershell -Command "Set-MpPreference -DisableRealtimeMonitoring 1"
```

Changes things dramatically:

![Screenshot 2021-04-16 at 19 59 02](https://user-images.githubusercontent.com/85709/115058731-3398f780-9eee-11eb-980b-3fc3d163b937.png)

**Comment by edigaryev** [comment]
Both `docker_builder` for Windows platform and `windows_container` should include the fix automatically now (thanks @fkorotkov!) and perhaps we can now close the https://github.com/cirruslabs/cirrus-ci-docs/issues/426 as well 🙌

**Comment by AlexWayfer** [comment]
I see significant performance change now!

https://cirrus-ci.com/task/5100892090269696?logs=ruby#L13

Although I can't check cache upload time, but I believe it's also smaller in times.

Thank you.
